version: 1
  backend:
    phases:
      preBuild:
        commands:
          - npm install
      build:
        commands:
          - npm run build
    artifacts:
      baseDirectory: dist
      files:
        - '**/*'
      discardPaths: no
    cache:
      paths:
        - node_modules/**/*
