name: Backend Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Backend
        run: npm run build

      - name: Check Build Output
        run: ls -la dist/

      - name: Verify Main File Exists
        run: test -f dist/index.js || (echo "Error: dist/index.js not found" && exit 1)
