name: Backend Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Build Backend
        run: npm run build
      - name: Check Build Output
        run: ls -la dist/
      - name: Verify Main File Exists
        run: |
          if [ ! -f dist/index.js ]; then
            echo "Error: dist/index.js not found"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: energy_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Initialize Database
        run: node test/setup-db.js
        env:
          PG_DBNAME: energy_db
          PG_USER: admin
          PG_PASSWORD: admin123
          PG_HOST: localhost
          PG_PORT: 5432
      - name: Run TypeScript Compilation
        run: npx tsc --project tsconfig.test.json
      - name: Fix Permissions & Run Mocha Tests
        run: |
          chmod +x ./node_modules/.bin/*
          node ./node_modules/mocha/bin/mocha.js test-dist/test/**/*.js --exit
      - name: Check Test Output
        if: failure()
        run: echo "Tests failed. Check the output above for details." && exit 1

  performance:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: energy_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Debug Scripts
        run: npm run
      - name: Build Backend
        run: npm run build
      - name: Start Server
        run: npm run start-server &
      - name: Wait for Server
        run: sleep 15
      - name: Check Server Status
        run: curl -I http://localhost:5000/ || echo "Server not running"
      - name: Run Performance Tests
        run: npm run performance:test
      - name: Check Performance Output
        if: failure()
        run: echo "Performance tests failed. Check the output above for details." && exit 1

  integration:
    runs-on: ubuntu-latest
    needs: test
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: energy_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Build Backend
        run: npm run build
      - name: Start Server
        run: npm run start-server &
      - name: Wait for Server
        run: sleep 15
      - name: Check Server Status
        run: curl -I http://localhost:5000/ || echo "Server not running"
      - name: Run Integration Tests
        run: npx tsc --project tsconfig.test.json && node ./node_modules/mocha/bin/mocha.js test-dist/test/**/*.js --exit
      - name: Check Integration Output
        if: failure()
        run: echo "Integration tests failed. Check the output above for details." && exit 1

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: energy_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones disabled for better relevancy of analysis
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Initialize Database
        run: node test/setup-db.js
        env:
          PG_DBNAME: energy_db
          PG_USER: admin
          PG_PASSWORD: admin123
          PG_HOST: localhost
          PG_PORT: 5432
      - name: Install nyc
        run: npm install --save-dev nyc
      - name: Run TypeScript Compilation
        run: npx tsc --project tsconfig.json
      - name: Debug API Initialization
        run: |
          if [ ! -f dist/index.js ]; then
            echo "Error: dist/index.js not found in /github/workspace"
            exit 1
          fi
          node -e "try { console.log(require('./dist/index').app); } catch (e) { console.error('Error:', e.message); }" > debug.log 2>&1
          cat debug.log
      - name: Run Coverage Tests with nyc
        run: |
          npx nyc --reporter=lcov --report-dir=coverage node ./node_modules/mocha/bin/mocha.js test-dist/test/**/*.js --exit
        env:
          PG_DBNAME: energy_db
          PG_USER: admin
          PG_PASSWORD: admin123
          PG_HOST: localhost
          PG_PORT: 5432
      - name: Check Coverage Report
        run: |
          ls -la coverage/ && cat coverage/lcov.info || echo "Coverage report not generated"
      - name: Disable Logging of Sensitive Data
        run: |
          export PG_DBNAME=energy_db
          export PG_USER=admin
          export PG_PASSWORD=admin123
          export PG_HOST=localhost
          export PG_PORT=5432
          node test/setup-db.js > /dev/null 2>&1
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=elmekadem-narjiss_Backen_ML
            -Dsonar.organization=elmekadem-narjiss
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
